# Stage 1
FROM node:18.15.0 as node

WORKDIR /app

COPY . .

RUN npm install
RUN npm run build --prod

# Stage 2
FROM nginx:alpine

COPY --from=node /app/dist/flashcard /usr/share/nginx/html

CMD ng serve --host 0.0.0.0
