FROM node:latest as node
WORKDIR /app
COPY . .
RUN npm install
RUN npm run build --prod

FROM nginx:alpine
COPY --from=node /app/dist/flashcard /usr/share/nginx/html
CMD ["nginx", "-g", "daemon off;"]
